library('MASS')
attach('survey')
pie(table(Smoke))
barplot(table(Smoke))
#pie(table(Sex, Smoke))
#barplot(table(Sex, Smoke), legend=T)
SMK=factor(Smoke, levels=levels(Smoke)[c(2,3,4,1)])
barplot(table(SMK))
barplot(table(Sex, SMK), beside=T, legend=T)
barplot(prop.table(table(Sex, SMK), 2), beside=T, legend=T)